#ifndef UARTMESSAGECODES_H_
#define UARTMESSAGECODES_H_

#define UARTDEVICESTART 0xA0
#define UARTSENDLASER 0xA1
#define UARTSENDSONIC 0xA2
#define UARTSENDMID 0xA3
#define UARTSENDANGLE 0xA4
#define UARTSTATEWORKRESPONSE 0xA5
#define UARTSTATEWAITRESPONSE 0xA6

#define UARTSTOPCOMMAND 0xB0
#define UARTSTARTCOMMAND 0xB1
#define UARTSTATEREQUEST 0xB2
#define UARTSETMINANG 0xB3
#define UARTSETMAXANG 0xB4
#define UARTSETSTEP 0xB5
#define UARTSELFDIAGNOSTIC 0xB6


#define UARTERRORLASERTIMEOUT 0xC1
#define UARTERRORSONICTIMEOUT 0xC2
#define UARTERRORLASEROUTOFRANGE 0xC3
#define UARTERRORSONICOUTOFRANGE 0xC4
#define UARTERRORMIDOUTOFRANGE 0xC5
#define UARTERRORSELFDIAGSONIC 0xC6
#define UARTERRORSELFDIAGLASER 0xC7
#define UARTERRORSELFDIAGMEM 0xC8

#endif /* UARTMESSAGECODES_H_ */